/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class GameTest {
    @Test
    public void shouldReturnFalseWhenGameisNotComplete() {
        Player playerOne = new Player("player 1");
        Player playerTwo = new Player("player 2");

        Game game = new Game(playerOne, playerTwo);
        assertFalse(game.isComplete());
    }
}
