/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class MatchTest {
    @Test
    public void matchShouldReturnScore(){
        Match match = new Match("player 1", "player 2");
        match.pointWonBy("player 1");
        Score score = match.score();

        assertEquals(0, score.playerOne());
    }
}
