/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class MatchTest {
    @Test
    public void matchShouldReturnScoreForNoPointsScored(){
        Match match = new Match("player 1", "player 2");

        assertEquals("0-0, 0-0", match.score());
    }

    @Test
    public void matchShouldReturnScoreWhenOneGameIsWonByPlayer(){
        Match match = new Match("player 1", "player 2");

        match.pointWonBy("player 1");
        match.pointWonBy("player 1");
        match.pointWonBy("player 1");
        match.pointWonBy("player 1");

        assertEquals("1-0", match.score());
    }
    @Test
    public void matchShouldReturnScoreWhenTwoGamesIsWonByPlayer(){
        Match match = new Match("player 1", "player 2");

        match.pointWonBy("player 1");
        match.pointWonBy("player 1");
        match.pointWonBy("player 1");
        match.pointWonBy("player 1");

        match.pointWonBy("player 2");
        match.pointWonBy("player 2");
        match.pointWonBy("player 2");
        match.pointWonBy("player 2");

        assertEquals("1-1", match.score());
    }

    @Test
    public void matchShouldReturnScoreWhenSecondGameIsOnGoing(){
        Match match = new Match("player 1", "player 2");

        match.pointWonBy("player 1");
        match.pointWonBy("player 1");
        match.pointWonBy("player 1");
        match.pointWonBy("player 1");

        match.pointWonBy("player 1");
        match.pointWonBy("player 2");
        match.pointWonBy("player 1");
        match.pointWonBy("player 2");

        assertEquals("1-0, 30-30", match.score());
    }
}
