/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class PlayerTest {
    @Test
    public void shouldReturnPlayerName(){
        Player player = new Player("player 1");

        assertEquals("player 1" , player.getName());
    }
}
