/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ScoreTest {
    @Test
    public void shouldReturnZeroAsInitialPoints() {
        Score score = new Score();

        assertEquals(0, score.points());
    }
    @Test
    public void shouldReturnPointsDescriptionFor0Points() {
        Score score = new Score();

        assertEquals(0, score.description());
    }
    @Test
    public void shouldReturnPointsDescriptionFor1Points() {
        Score score = new Score(1);

        assertEquals(15, score.description());
    }
    @Test
    public void shouldReturnPointsDescriptionFor2Points() {
        Score score = new Score(2);

        assertEquals(30, score.description());
    }
    @Test
    public void shouldReturnPointsDescriptionFor3Points() {
        Score score = new Score(3);

        assertEquals(40, score.description());
    }
    @Test
    public void shouldReturnPointsDescriptionFor4Points() {
        Score score = new Score(4);

        assertEquals(60, score.description());
    }
    @Test
    public void scoresShouldBeEqualWhenPointsAreSame() {
        Score score1 = new Score(4);
        Score score2 = new Score(4);

        assertEquals(score1, score2);
    }
    @Test
    public void shouldReturnScoreWhenPointIsScored() {
        Score score = new Score();
        score.pointScored();
        Score score2 = new Score(1);

        assertEquals(score2, score);
    }
}
